//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPLOYEE_NUMBER { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public Nullable<int> SALARY { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
