//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDANGERED_SPECIES
    {
        public short SPECIES_ID { get; set; }
        public string COMMON_NAME { get; set; }
        public string SCIENTIFIC_NAME { get; set; }
    }
}
