//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOGADJAJ> DOGADJAJs { get; set; }
        public DbSet<PROJEKAT> PROJEKATs { get; set; }
        public DbSet<REZ> REZs { get; set; }
        public DbSet<REZERVISANO_SEDISTE> REZERVISANO_SEDISTE { get; set; }
        public DbSet<SALA> SALAs { get; set; }
        public DbSet<SEDISTE> SEDISTEs { get; set; }
        public DbSet<SKOLA> SKOLAs { get; set; }
        public DbSet<TIP_DELO> TIP_DELO { get; set; }
        public DbSet<TIP_REZ> TIP_REZ { get; set; }
        public DbSet<TIP_VIP> TIP_VIP { get; set; }
        public DbSet<TIP_ZAP> TIP_ZAP { get; set; }
        public DbSet<U_GALERIJI> U_GALERIJI { get; set; }
        public DbSet<U_SALI> U_SALI { get; set; }
        public DbSet<UMETNICKO_DELO> UMETNICKO_DELO { get; set; }
        public DbSet<VIP> VIPs { get; set; }
        public DbSet<ZAP> ZAPs { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public DbSet<ENDANGERED_SPECIES> ENDANGERED_SPECIES { get; set; }
        public DbSet<RADNIK> RADNIKs { get; set; }
        public DbSet<RADPROJ> RADPROJs { get; set; }
    }
}
