//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNIK
    {
        public RADNIK()
        {
            this.PROJEKATs = new HashSet<PROJEKAT>();
            this.RADNIK1 = new HashSet<RADNIK>();
            this.RADPROJs = new HashSet<RADPROJ>();
        }
    
        public decimal MBR { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public Nullable<decimal> SEF { get; set; }
        public Nullable<decimal> PLT { get; set; }
        public Nullable<decimal> PRE { get; set; }
        public System.DateTime GOD { get; set; }
    
        public virtual ICollection<PROJEKAT> PROJEKATs { get; set; }
        public virtual ICollection<RADNIK> RADNIK1 { get; set; }
        public virtual RADNIK RADNIK2 { get; set; }
        public virtual ICollection<RADPROJ> RADPROJs { get; set; }
    }
}
