//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZ
    {
        public REZ()
        {
            this.REZERVISANO_SEDISTE = new HashSet<REZERVISANO_SEDISTE>();
        }
    
        public string IDREZ { get; set; }
        public string REZERVISANO { get; set; }
        public string PLACENO { get; set; }
        public string U_SALI_ID_DOG { get; set; }
        public string ZAP_ID_ZAP1 { get; set; }
        public string ZAP_ID_ZAP { get; set; }
        public string TIP_REZ_ID_TIP_REZ { get; set; }
        public string VIP_TIP_VIP_ID_TIP_VIP { get; set; }
        public string SKOLA_ID_SKOLA { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public string ZAP_TIP_ZAP_IDTIPZAP1 { get; set; }
        public string ZAP_TIP_ZAP_IDTIPZAP { get; set; }
    
        public virtual SKOLA SKOLA { get; set; }
        public virtual TIP_REZ TIP_REZ { get; set; }
        public virtual U_SALI U_SALI { get; set; }
        public virtual VIP VIP { get; set; }
        public virtual ZAP ZAP { get; set; }
        public virtual ZAP ZAP1 { get; set; }
        public virtual ICollection<REZERVISANO_SEDISTE> REZERVISANO_SEDISTE { get; set; }
    }
}
