//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_REZ
    {
        public TIP_REZ()
        {
            this.REZs = new HashSet<REZ>();
        }
    
        public string ID_TIP_REZ { get; set; }
        public string NAZIV { get; set; }
    
        public virtual ICollection<REZ> REZs { get; set; }
    }
}
