//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_ZAP
    {
        public TIP_ZAP()
        {
            this.ZAPs = new HashSet<ZAP>();
        }
    
        public string IDTIPZAP { get; set; }
        public string NAZIV { get; set; }
    
        public virtual ICollection<ZAP> ZAPs { get; set; }
    }
}
