//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_VIP
    {
        public string ID_TIP_VIP { get; set; }
        public string NAZIV { get; set; }
    
        public virtual VIP VIP { get; set; }
    }
}
