//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_GALERIJI
    {
        public U_GALERIJI()
        {
            this.DOGADJAJs = new HashSet<DOGADJAJ>();
            this.UMETNICKO_DELO = new HashSet<UMETNICKO_DELO>();
            this.UMETNICKO_DELO1 = new HashSet<UMETNICKO_DELO>();
            this.VIPs = new HashSet<VIP>();
        }
    
        public string ID_DOG { get; set; }
        public string NAZIV { get; set; }
        public decimal GODINA { get; set; }
        public string KONTAKT_IME { get; set; }
        public string KONTAKT_PRZ { get; set; }
        public string KONTAKT_BROJ { get; set; }
        public System.DateTime DATUM { get; set; }
        public string REALIZOVANO { get; set; }
        public string VODITELJ_IME { get; set; }
        public string VODITELJ_PRZ { get; set; }
        public Nullable<decimal> VODITELJ_BROJ { get; set; }
    
        public virtual ICollection<DOGADJAJ> DOGADJAJs { get; set; }
        public virtual ICollection<UMETNICKO_DELO> UMETNICKO_DELO { get; set; }
        public virtual ICollection<UMETNICKO_DELO> UMETNICKO_DELO1 { get; set; }
        public virtual ICollection<VIP> VIPs { get; set; }
    }
}
