//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SALI
    {
        public U_SALI()
        {
            this.DOGADJAJs = new HashSet<DOGADJAJ>();
            this.REZs = new HashSet<REZ>();
        }
    
        public string ID_DOG { get; set; }
        public string NAZIV { get; set; }
        public decimal GODINA { get; set; }
        public string KONTAKT_IME { get; set; }
        public string KONTAKT_PRZ { get; set; }
        public string KONTAKT_BROJ { get; set; }
        public System.DateTime DATUM { get; set; }
        public string REALIZOVANO { get; set; }
        public Nullable<decimal> ZARADA { get; set; }
        public Nullable<decimal> POSECENOST { get; set; }
        public Nullable<decimal> CENA_KARTE { get; set; }
        public string TITL { get; set; }
        public string OPREMA { get; set; }
    
        public virtual ICollection<DOGADJAJ> DOGADJAJs { get; set; }
        public virtual ICollection<REZ> REZs { get; set; }
    }
}
