//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP
    {
        public VIP()
        {
            this.REZs = new HashSet<REZ>();
            this.U_GALERIJI = new HashSet<U_GALERIJI>();
        }
    
        public string ID_VIP { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public Nullable<decimal> BROJ_TEL { get; set; }
        public string EMAIL { get; set; }
        public string ADRESA { get; set; }
        public string IDREZ { get; set; }
        public string ID_DOG { get; set; }
        public string TIP_VIP_ID_TIP_VIP { get; set; }
    
        public virtual ICollection<REZ> REZs { get; set; }
        public virtual TIP_VIP TIP_VIP { get; set; }
        public virtual ICollection<U_GALERIJI> U_GALERIJI { get; set; }
    }
}
