//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAP
    {
        public ZAP()
        {
            this.REZs = new HashSet<REZ>();
            this.REZs1 = new HashSet<REZ>();
        }
    
        public string ID_ZAP { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public string KORISNICKO_IME { get; set; }
        public string LOZINKA { get; set; }
        public Nullable<decimal> BROJ_TEL { get; set; }
        public string EMAIL { get; set; }
        public string ADRESA { get; set; }
        public string TIP_ZAP_IDTIPZAP { get; set; }
    
        public virtual ICollection<REZ> REZs { get; set; }
        public virtual ICollection<REZ> REZs1 { get; set; }
        public virtual TIP_ZAP TIP_ZAP { get; set; }
    }
}
